apiVersion: v1
kind: Secret
metadata:
  name: omega-backstage-secrets
  namespace: backstage
type: Opaque
#data:
#  GITHUB_TOKEN: LW4gJ2docF9kTE9lMDU4NkVmVWdZZk1xWkJYVUlNZDlNaUlES2g0TjdManYnIA0K
#  AZURE_CLIENT_ID: LW4gJ2I4MTk0NWJiLWRlMzUtNDY2NS1iYjY3LWIxZmY4ZDY3NzliNycgDQo=
# AZURE_CLIENT_SECRET: LW4gJ1RyWDhRfklZTml1QXBnLW1hX3QxS3VVRXdIS2VJUVlmTjZxSGFkbTgnIA0K
# AZURE_TENANT_ID: LW4gJzU2ZmRlN2NmLTMzNzUtNDBjNS1hZjQ2LTgzNjZmOTZkMzA2NicgDQo=
stringData:
  GITHUB_TOKEN: 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
  AZURE_CLIENT_ID: b81945bb-de35-4665-bb67-b1ff8d6779b7
  AZURE_CLIENT_SECRET: TrX8Q~IYNiuApg-ma_t1KuUEwHKeIQYfN6qHadm8
  AZURE_TENANT_ID: 56fde7cf-3375-40c5-af46-8366f96d3066
  HOST: localhost
  ORG_NAME: ADM Group
  TITLE: Backstage