global:
  imageRegistry: manojkumar1980/backstage-adm
  pullPolicy: IfNotPresent
backstage: 
  replicas: 1  
  extraEnvVarsSecrets: ['postgress-secrets','backstage-secrets']    
  appConfig:
    app:      
      title: ${TITLE}   
      baseUrl: http://${HOST}:7007
    organization:
      name: ${ORG_NAME}    
    backend:
      baseUrl: http://${HOST}:7007
      csp:
        connect-src: ["'self'", 'http:', 'https:']
        # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
        # Default Helmet Content-Security-Policy values can be removed by setting the key to false
      cors:
        origin: http://${HOST}:7007
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      database:
        client: pg  
        ensureExists: true     
        connection:
          database: ${POSTGRES_DB}
          host: ${POSTGRES_HOST}
          port: ${POSTGRES_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}        
    auth:
      microsoft:
        clientId: ${AZURE_CLIENT_ID}
        clientSecret: ${AZURE_CLIENT_SECRET}
        tenantId: ${AZURE_TENANT_ID}
    # see https://backstage.io/docs/auth/ to learn about auth providers
      environment: production
      providers:
        microsoft:
          production:
            clientId: ${AZURE_CLIENT_ID}
            clientSecret: ${AZURE_CLIENT_SECRET}
            tenantId: ${AZURE_TENANT_ID}
    integrations:
      github:
        - host: github.com
          # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
          # about setting up the GitHub integration here: https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration
          token: ${GITHUB_TOKEN}
    techdocs:
      builder: 'local'   
      generator:
        runIn: 'local'           
    catalog:      
      locations:    
        - type: url
          target: https://github.com/manoj136/backstage-poc/blob/main/packages/catalog-model/examples/all.yaml          