apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-key-vault-service-provider
  namespace: kube-system
spec:
  provider: azure
  parameters: 
    usePodIdentity: "false" # [REQUIRED] Set to "true" if using managed identities    
    keyvaultName: minikube-integration-poc
    # Azure AD tenant ID. Received when we created the SP.
    tenantId: 56fde7cf-3375-40c5-af46-8366f96d3066
    resourceGroup: Minikube-Key-Vault-Poc-grp
    subscriptionId: 3736510e-28ca-4a77-954c-bb9228d15abf
    # List of secrets to pull from the key vault 
    objects: |
      array:
        - |
          objectName: POSTGRES-USER
          objectType: secret
        - |
          objectName: POSTGRES-PASSWORD
          objectType: secret
  # The new Kubernetes secret to create
  secretObjects:
  # Name of the new Kubernetes secret
    - secretName: azure-key-vault-secrets      
      type: Opaque
      data:
        # A key name inside the new secret
        - key: pg-user
          # Secret value to use
          objectName: POSTGRES-USER
        - key: pg-password
          objectName: POSTGRES-PASSWORD