apiVersion: v1
kind: PersistentVolume
metadata:
  name: aspnetcore-minimalapi-debug-test-pod-pv
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/aspnetcore/minimal-api/bin"
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: manual
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120