kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aspnetcore-minimalapi-debug-test-pod-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: aspnetcore-minimalapi-debug-test-pod-pv
  storageClassName: manual