apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aspnetcore-minikube-secret-provider
  namespace: default
spec:
  provider: azure
  parameters: 
    usePodIdentity: "false" # [REQUIRED] Set to "true" if using managed identities   
    #useVMManagedIdentity: "true"         
    #userAssignedIdentityID: a420bfa8-4206-4695-ba8c-f6a71dd37240 
    keyvaultName: minikube-integration-poc
    # Azure AD tenant ID. Received when we created the SP.
    tenantId: 56fde7cf-3375-40c5-af46-8366f96d3066
    #resourceGroup: Minikube-Key-Vault-Poc-grp
    #subscriptionId: 3736510e-28ca-4a77-954c-bb9228d15abf
    # List of secrets to pull from the key vault 
    objects: |
      array:
        - |
          objectName: POSTGRES-USER
          objectAlias: POSTGRES-USER-ALIAS
          objectType: secret
        - |
          objectName: POSTGRES-PASSWORD
          objectAlias: POSTGRES-PASSWORD-ALIAS
          objectType: secret
  # The new Kubernetes secret to create
  secretObjects:
  # Name of the new Kubernetes secret   
      - data:          
            # Secret value to use
          - objectName: POSTGRES-USER-ALIAS
            # A key name inside the new secret
            key: pg-user
          - objectName: POSTGRES-PASSWORD-ALIAS 
            key: pg-password         
        secretName: azure-key-vault-secrets      
        type: Opaque