apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-apis
  description: A collection of all Backstage example APIs
spec:
  targets:   
    - ./apis/petstore-api.yaml   
    - ./apis/spotify-api.yaml
    - ./apis/botify-api.yaml