apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: az-blob-integration-minikube-poc-storage-blobfuse
  namespace: kube-system
provisioner: blob.csi.azure.com
parameters:
  resourceGroup: azure-blob-storage-minikube-rg
  storageAccount: azureblobstorageaccmk
  containerName: azure-blob-integration-mk-poc-conatiner
  #protocol: nfs
  tags: environment=minikube-poc
volumeBindingMode: Immediate
allowVolumeExpansion: true
reclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
mountOptions:
  - -o allow_other
  - --file-cache-timeout-in-seconds=120
  - --use-attr-cache=true
  - --cancel-list-on-mount-seconds=60  # prevent billing charges on mounting
  - -o attr_timeout=120
  - -o entry_timeout=120
  - -o negative_timeout=120
  - --cache-size-mb=1000  # Default will be 80% of available memory, eviction will happen beyond that.