apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: az-blob-integration-minikube-poc-pv
  namespace: kube-system
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: az-blob-integration-minikube-poc-storage-blobfuse
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure volumeid is unique for every identical storage blob container in the cluster. 
    # standard way of naming convetion is {account-name}_{container-name}
    # character `#` is reserved for internal use and cannot be used in volumehandle
    volumeHandle: 70f97163-98e1-4d21-a04b-ad31957d6496
    volumeAttributes:
      resourceGroup: azure-blob-storage-minikube-rg
      storageAccount: azureblobstorageaccmk
      containerName: azure-blob-integration-mk-poc-conatiner     
    nodeStageSecretRef:
      name: azure-blob-secret
      namespace: kube-system