apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbit-mq-cluster-poc-import-user-permission
  namespace: rabbitmq-system
spec:
  vhost: "/"
  user: "admin"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbit-mq-cluster-poc