apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit-mq-cluster-poc
  namespace: rabbitmq-system
  labels:
    app: rabbit-mq-cluster-poc
spec:  
  replicas: 1     
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  rabbitmq:
      additionalConfig: |
              log.console.level = debug
  service:
    type: LoadBalancer